### ISSUE TITLE
About data preprocessing

### ISSUE THREAD

**Issue by 4fee8fea** [yyyyangyi/Multi-source-RS-DGConv#1]
Thanks for your work and code!

Here are some codes within `dataset_muufl.py`:
```
data_lidar = scio.loadmat(os.path.join(data_dir, 'lidar_data.mat'))['lidar_data']
data_hsi = scio.loadmat(os.path.join(data_dir, 'hsi_data.mat'))['hsi_data']
labels = scio.loadmat(os.path.join(data_dir, 'labels.mat'))['labels']
```
I have downloaded `MUUFLGulfport` dataset, whereas no direct files `lidar_data.mat`, `hsi_data.mat`, `labels.mat` exist.

The same question occurs in `dataset_houston.py`, `dataset_berlin.py`.

Could you please tell me what preprocessings should be done for the raw dataset?

Thanks a lot!

**Comment by yyyyangyi** [comment]
Hi, 

Thanks for your interest in our work. 

For `MUUFL` dataset, the original data file contains a large MatLab dictionary, and we extracted useful information and stored in _lidar_data.mat_, _hsi_data.mat_, and _labels.mat_. For `Houston2018` dataset, the original training set is composed of multiple data files (hyperspectral, lidar, etc., in tiff format), and in our _.npy_ files we simply stacked them together using Numpy arrays. For `Berlin` dataset, we directly use the original data files. 

Please note that we further processed the data using channel-wise normalization AFTER loading data files mentioned above. This part of preprocessing is already implemented in our code, and all you need to do is to load the data files. You might want to take a look at our paper Section III.B if you are interested in more details of preprocessing. 

In addition, we have provided a link to data files that can be directly loaded by our code. 

Please feel free to contact us if you have any further questions or suggestions!
